#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod erc20;
pub mod lp_pair;
pub mod uni_v2_factory;
pub mod uni_v2_router;
